### PR TITLE
Routiers Mercenary Class

### PR DESCRIPTION
**Pull request by sylphynford**
## About The Pull Request

The Otavan Routiers are a new unique noble merc class with all new custom armor sprites. This is a specialized class focused on defense, taking hits and protecting others. If Grenzelhoft is the offensive merc, Routiers are the defensive one. They also have noble blood (without a mammon estate bonus).  Their strength is relatively low compared to other mercs, but this is made up for with very high CON, leaning into the defensive purpose. 
The corset on the armor may be toggled on and off via right click. 
Subclasses:
Swordsman, receives a falchion (a new weapon with a quilloned crossguard, deals less damage than a longsword but more defense) and sword skill, along with other generic merc skills.
Macebearer, receives a morningstar
Flailman, receives a steel flail

Not available to short races due to the lack of dwarf sprites for the gear. 

## Why It's Good For The Game

Cool looking new armor sprites along with new roleplay opportunities for mercenaries via having noble blood.

### CODE REVIEW

**Review by AllCorruptingWyrm — CHANGES_REQUESTED** [review]
Could you pretty please add the sprite sheet to the original pr please? And clarify this was a commission in the job file so no one messes with the sprites and claim it as their own.

Otherwise I really like it. Good work!

**Comment by sylphynford** [comment]
Is that suitable?

**Comment by AllCorruptingWyrm** [comment]
4 in anything isnt that bad less its for a merc so all in all its good. Just going to let it sit.

**Review by AllCorruptingWyrm — APPROVED** [review]
This is good to be merged to provide the void that knight errant will provide. You can go ahead and make them less "good" off the bat.

**Comment by AllCorruptingWyrm** [comment]
This is not setting the standard that donations = class.
This is a replacement for the niche knight errant occupied.

**Pull request merged**
